t_scene_info = [
	[cutscene_create_dialogue,conversation_4()],
	[create_box_at_mouse],
	[cutscene_create_dialogue,conversation_5()],
	[create_box_at_mouse],	
	[cutscene_create_dialogue,conversation_6()],
	[create_box_at_mouse],	
	[cutscene_create_dialogue,conversation_7()],
	[create_box_at_mouse],	
	[cutscene_create_dialogue,conversation_8()],
	[create_box_at_mouse],	
	[cutscene_create_dialogue,conversation_9()],
	[create_box_at_mouse],	
	[cutscene_create_dialogue,conversation_10()],
	[create_box_at_mouse],	
	[cutscene_create_dialogue,conversation_11()],
]